variables:
  # InjectAlmOctaneTasks: 'true'
  OctaneConnectionName: 'qa8'
  WS_ID: '1002'
  GithubRepositoryConnection: 'maya_git_acces'


jobs:
- job: AlmOctanePipelineStart
  condition: always()
  steps:
  - task: octane-start-task@1
    inputs:
      OctaneServiceConnection: $(OctaneConnectionName)
      WorkspaceList: $(WS_ID)
      GithubRepositoryConnection: $(GithubRepositoryConnection)

- job: A
  steps:
  - script: echo Hello, Job A!
    displayName: 'Run a one-line script'
  dependsOn:
  - AlmOctanePipelineStart

- job: B
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: AlmOctanePipelineEnd
  condition: always()
  steps:
  - task: octane-end-task@1
    inputs:
      OctaneServiceConnection: $(OctaneConnectionName)
      WorkspaceList: $(WS_ID)
      GithubRepositoryConnection: $(GithubRepositoryConnection)

  dependsOn:
  - AlmOctanePipelineStart
  - A
  - B